import type { User } from '../contracts';
import { ApiError } from './errors';
import { appOrigin, authConfigured, database, type Env } from './env';
import { randomToken, safeReturnTo, sha256 } from './security';
const SESSION='migos_session';const OAUTH='migos_oauth';
export function cookie(request:Request,name:string){return request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1);}
export function setCookie(name:string,value:string,env:Env,maxAge:number){return `${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${appOrigin(env).startsWith('https:')?'; Secure':''}`;}
export async function currentUser(request:Request,env:Env):Promise<(User&{credits:number})|null>{const token=cookie(request,SESSION);if(!env.DB||!token||!/^[\w-]{43}$/.test(token))return null;return env.DB.prepare('SELECT u.id,u.name,u.email,u.picture,u.credits FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>unixepoch()').bind(await sha256(token)).first<User&{credits:number}>();}
export async function requireUser(request:Request,env:Env){const user=await currentUser(request,env);if(!user)throw new ApiError(401,'Please sign in to continue.');return user;}
export async function startGoogle(request:Request,env:Env){if(!authConfigured(env))throw new ApiError(503,'Google sign-in is not configured yet.');if(request.headers.get('sec-fetch-site')==='cross-site')throw new ApiError(403,'Start sign-in from this website.');const db=database(env),state=randomToken(),verifier=randomToken();const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');await db.prepare('INSERT INTO oauth_states(state_hash,verifier,return_to,expires_at) VALUES(?,?,?,unixepoch()+600)').bind(await sha256(state),verifier,safeReturnTo(new URL(request.url).searchParams.get('returnTo'))).run();const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID!,redirect_uri:appOrigin(env)+'/api/auth/callback/google',response_type:'code',scope:'openid email profile',state,code_challenge:challenge,code_challenge_method:'S256'}).toString();return new Response(null,{status:302,headers:{Location:url.href,'Set-Cookie':setCookie(OAUTH,state,env,600),'Cache-Control':'no-store'}});}
export async function finishGoogle(request:Request,env:Env){if(!authConfigured(env))throw new ApiError(503,'Google sign-in is not configured yet.');const url=new URL(request.url),state=url.searchParams.get('state'),code=url.searchParams.get('code');if(!state||state!==cookie(request,OAUTH)||!code)throw new ApiError(400,'Sign-in expired or was cancelled. Please try again.');const db=database(env);const saved=await db.prepare('DELETE FROM oauth_states WHERE state_hash=? AND expires_at>unixepoch() RETURNING verifier,return_to').bind(await sha256(state)).first<{verifier:string;return_to:string}>();if(!saved)throw new ApiError(400,'Sign-in has expired. Please try again.');const tokenResponse=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID!,client_secret:env.GOOGLE_CLIENT_SECRET!,redirect_uri:appOrigin(env)+'/api/auth/callback/google',grant_type:'authorization_code',code_verifier:saved.verifier}),signal:AbortSignal.timeout(15000)});if(!tokenResponse.ok)throw new ApiError(502,'Google could not complete sign-in.');const tokens=await tokenResponse.json() as {access_token?:string};if(!tokens.access_token)throw new ApiError(502,'Google did not return a sign-in token.');const profileResponse=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${tokens.access_token}`},signal:AbortSignal.timeout(15000)});if(!profileResponse.ok)throw new ApiError(502,'Google could not verify your profile.');const profile=await profileResponse.json() as {sub?:string;email?:string;email_verified?:boolean;name?:string;picture?:string};if(!profile.sub||!profile.email||profile.email_verified!==true)throw new ApiError(403,'A verified Google email is required.');
 await db.prepare('INSERT INTO users(id,email,name,picture,google_sub) VALUES(?,?,?,?,?) ON CONFLICT(google_sub) DO UPDATE SET name=excluded.name,picture=excluded.picture').bind(crypto.randomUUID(),profile.email,profile.name??profile.email,profile.picture??null,profile.sub).run();const user=await db.prepare('SELECT id FROM users WHERE google_sub=?').bind(profile.sub).first<{id:string}>();if(!user)throw new ApiError(503,'Could not establish a session.');await db.prepare("INSERT INTO credit_ledger(id,user_id,amount,kind,reference_id) VALUES(?,?,10,'welcome',?) ON CONFLICT(kind,reference_id) DO NOTHING").bind(user.id+':welcome',user.id,user.id).run();const token=randomToken();await db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,unixepoch()+2592000)').bind(await sha256(token),user.id).run();const headers=new Headers({Location:appOrigin(env)+safeReturnTo(saved.return_to),'Cache-Control':'no-store'});headers.append('Set-Cookie',setCookie(SESSION,token,env,2592000));headers.append('Set-Cookie',setCookie(OAUTH,'',env,0));return new Response(null,{status:302,headers});}
export async function logout(request:Request,env:Env){const token=cookie(request,SESSION);if(env.DB&&token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run();return Response.json({ok:true},{headers:{'Set-Cookie':setCookie(SESSION,'',env,0),'Cache-Control':'no-store'}});}
