import { creditPacks } from '../../content/pricing';
import { appOrigin,database,type Env } from './env';
import { ApiError } from './errors';
import type { User } from '../contracts';
type Order={id:string;user_id:string;pack_id:string;product_id:string;amount:number;currency:string;credits:number;checkout_id:string|null;provider_order_id:string|null;status:string};
export async function createCheckout(env:Env,user:User,packId:unknown){const pack=creditPacks.find(p=>p.id===packId);if(!pack)throw new ApiError(400,'Unknown credit pack.');const product=env[`CREEM_PRODUCT_${pack.id.toUpperCase()}` as keyof Env];if(!env.CREEM_API_KEY||typeof product!=='string'||!product)throw new ApiError(503,'Checkout is not configured for this credit pack.');if(!['test','production'].includes(env.CREEM_MODE??''))throw new ApiError(503,'Checkout environment is not configured.');const db=database(env),id=crypto.randomUUID();await db.prepare('INSERT INTO orders(id,user_id,pack_id,product_id,amount,currency,credits) VALUES(?,?,?,?,?,?,?)').bind(id,user.id,pack.id,product,pack.amountCents,'USD',pack.credits).run();let response:Response;try{response=await fetch((env.CREEM_MODE==='test'?'https://test-api.creem.io':'https://api.creem.io')+'/v1/checkouts',{method:'POST',headers:{'x-api-key':env.CREEM_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({product_id:product,request_id:id,customer:{email:user.email},success_url:appOrigin(env)+'/pricing?checkout=completed&orderId='+encodeURIComponent(id),metadata:{userId:user.id,packId:pack.id}}),signal:AbortSignal.timeout(20000),redirect:'manual'});}catch{throw new ApiError(502,'Checkout creation could not be confirmed. Please try again later.');}if(!response.ok){await response.body?.cancel().catch(()=>{});throw new ApiError(502,'The payment service could not create checkout.');}const body=await response.json() as {id?:string;checkout_url?:string};if(!body.id||!body.checkout_url)throw new ApiError(502,'The payment service returned an incomplete checkout.');const url=new URL(body.checkout_url);if(url.protocol!=='https:'||!(url.hostname==='creem.io'||url.hostname.endsWith('.creem.io')))throw new ApiError(502,'Invalid checkout address.');await db.prepare('UPDATE orders SET checkout_id=? WHERE id=?').bind(body.id,id).run();return {checkoutUrl:url.href,orderId:id};}
export async function applyCheckout(db:D1Database,event:any):Promise<void>{const c=event?.object;if(typeof event?.id!=='string'||event.eventType!=='checkout.completed'||!c||typeof c.request_id!=='string')throw new ApiError(400,'Invalid payment event.');const row=await db.prepare('SELECT * FROM orders WHERE id=?').bind(c.request_id).first<Order>();const product=typeof c.order?.product==='string'?c.order.product:c.order?.product?.id;
 if(!row||c.status!=='completed'||c.order?.status!=='paid'||typeof c.order.id!=='string'||c.product?.id!==row.product_id||product!==row.product_id||c.metadata?.userId!==row.user_id||c.metadata?.packId!==row.pack_id||c.order.amount!==row.amount||c.order.currency?.toUpperCase()!==row.currency||typeof c.id!=='string'||row.checkout_id&&row.checkout_id!==c.id||row.provider_order_id&&row.provider_order_id!==c.order.id)throw new ApiError(400,'Payment does not match the recorded order.');
 await db.batch([
 db.prepare("UPDATE orders SET status='paid',checkout_id=?,provider_order_id=? WHERE id=? AND status IN('pending','paid')").bind(c.id,c.order.id,row.id),
 db.prepare("INSERT INTO credit_ledger(id,user_id,amount,kind,reference_id) SELECT id||':payment',user_id,credits,'payment',id FROM orders WHERE id=? AND status='paid' ON CONFLICT(kind,reference_id) DO NOTHING").bind(row.id),
 db.prepare('INSERT INTO webhook_events(id,event_type,order_id) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(event.id,event.eventType,row.id)
 ]);}
export async function recordReviewEvent(db:D1Database,event:any){await db.prepare('INSERT INTO webhook_events(id,event_type,review_required,note) VALUES(?,?,1,?) ON CONFLICT(id) DO NOTHING').bind(event.id,event.eventType,JSON.stringify({message:'Manual reconciliation required; no automatic credit adjustment.',refundId:event.object?.id,transactionId:event.object?.transaction?.id,amount:event.object?.refund_amount??event.object?.amount,currency:event.object?.refund_currency,status:event.object?.status})).run();}
