import { describe,it,expect,vi } from 'vitest';
import { database,jobEnv } from './helpers';
import { reserveGeneration } from '../lib/server/billing';
import { advanceJob } from '../lib/server/jobs';
import { storeProviderMedia } from '../lib/server/media';
function gate(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return {promise,resolve};}
function pauseSnapshot(db:D1Database){const arrived=gate(),resume=gate();let paused=false;const prepare=db.prepare.bind(db);const wrapped={...db,prepare(sql:string){const stmt=prepare(sql);const bind=stmt.bind.bind(stmt);stmt.bind=(...args:any[])=>{const bound=bind(...args);const first=bound.first.bind(bound);bound.first=async()=>{const result=await first();if(!paused&&sql.startsWith('SELECT * FROM generations WHERE id=')){paused=true;arrived.resolve();await resume.promise;}return result;};return bound;};return stmt;}} as D1Database;return {db:wrapped,arrived,resume};}
async function readyJob(){const d=database();const j=await reserveGeneration(d.db,'u','lease-race','video',{leftImage:'a',rightImage:'b',duration:5,aspect:'9:16',resolution:'480p'},50);d.sqlite.prepare("UPDATE generations SET stage='ready',assets=? WHERE id=?").run(JSON.stringify([{url:'asset://left'},{url:'asset://right'}]),j.id);return {...d,id:j.id};}
describe('lease expiry regressions',()=>{
 it('fences a stale ready snapshot before a second paid POST',async()=>{const d=await readyJob(),pause=pauseSnapshot(d.db);let posts=0;const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>Response.json({data:[{task_id:`task_${++posts}`}]}));try{const old=advanceJob(jobEnv(pause.db),d.id);await pause.arrived.promise;d.sqlite.exec('UPDATE generations SET lease_until=0,next_poll=0');await advanceJob(jobEnv(d.db),d.id);pause.resume.resolve();await old;expect(posts).toBe(1);expect(d.sqlite.prepare('SELECT provider_id FROM generations').get()?.provider_id).toBe('task_1');}finally{pause.resume.resolve();fetcher.mockRestore();}});
 it('does not let an old finally release a newer active lease',async()=>{const d=await readyJob(),pause=pauseSnapshot(d.db),posting=gate(),complete=gate();let calls=0;const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>{if(++calls===1){posting.resolve();await complete.promise;}return Response.json({data:[{task_id:'new'}]});});try{const old=advanceJob(jobEnv(pause.db),d.id);await pause.arrived.promise;d.sqlite.exec('UPDATE generations SET lease_until=0,next_poll=0');const fresh=advanceJob(jobEnv(d.db),d.id);await posting.promise;pause.resume.resolve();await old;expect(Number(d.sqlite.prepare('SELECT lease_until FROM generations').get()?.lease_until)).toBeGreaterThan(Date.now()/1000);complete.resolve();await fresh;}finally{pause.resume.resolve();complete.resolve();fetcher.mockRestore();}});
});
describe('avatar query retries',()=>{
 for(const failure of ['503','429','network','json'])it(`retains review task after ${failure}, then resumes successfully`,async()=>{const d=database(),j=await reserveGeneration(d.db,'u',failure,'video',{},50);d.sqlite.prepare("UPDATE generations SET stage='reviewing',status='reviewing',assets=? WHERE id=?").run(JSON.stringify([{key:'a',side:'left',taskId:'avatar_1'},{key:'b',side:'right',url:'asset://right'}]),j.id);const fetcher=vi.spyOn(globalThis,'fetch').mockImplementationOnce(async()=>{if(failure==='network')throw new TypeError('network');return new Response(failure==='json'?'invalid':'unavailable',{status:failure==='json'?200:Number(failure)});}).mockResolvedValue(Response.json({data:{status:'completed',result:{usable_assets:[{asset_url:'asset://left'}]}}}));try{await advanceJob(jobEnv(d.db),j.id);expect(d.sqlite.prepare('SELECT status FROM generations').get()?.status).toBe('reviewing');expect(d.sqlite.prepare('SELECT credits FROM users').get()?.credits).toBe(50);d.sqlite.exec('UPDATE generations SET next_poll=0');await advanceJob(jobEnv(d.db),j.id);expect(d.sqlite.prepare('SELECT stage FROM generations').get()?.stage).toBe('ready');}finally{fetcher.mockRestore();}});
});
function multipartBucket(options:{failPart?:boolean;beforeComplete?:()=>Promise<void>}={}){let largest=0,total=0,completed=0,aborted=0;const bucket={async createMultipartUpload(){return {uploadId:'upload',key:'key',async uploadPart(partNumber:number,value:Uint8Array){largest=Math.max(largest,value.byteLength);total+=value.byteLength;if(options.failPart)throw new Error('R2 unavailable');return {partNumber,etag:'part'};},async complete(){await options.beforeComplete?.();completed++;return {};},async abort(){aborted++;}};},async put(_key:string,value:Uint8Array){largest=value.byteLength;total=value.byteLength;await options.beforeComplete?.();completed++;return {};}} as unknown as R2Bucket;return {bucket,stats:()=>({largest,total,completed,aborted})};}
function videoResponse(mib:number,length=false){let n=0;return new Response(new ReadableStream<Uint8Array>({pull(controller){if(n++===mib){controller.close();return;}controller.enqueue(new Uint8Array(1024*1024));}}),{headers:{'content-type':'video/mp4',...(length?{'content-length':String(mib*1024*1024)}:{})}});}
describe('bounded media streaming',()=>{
 it('streams two concurrent 64 MiB chunked results in bounded multipart buffers',async()=>{const r=multipartBucket(),fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>videoResponse(64));try{await Promise.all([1,2].map(i=>storeProviderMedia({...jobEnv({} as D1Database),MEDIA:r.bucket},'https://cdn.apimart.ai/video',String(i),'video')));expect(r.stats().largest).toBeLessThanOrEqual(5*1024*1024);expect(r.stats().total).toBe(128*1024*1024);expect(r.stats().completed).toBe(2);}finally{fetcher.mockRestore();}});
 it('aborts an oversized chunked upload without committing an object',async()=>{const r=multipartBucket(),fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(videoResponse(65));try{await expect(storeProviderMedia({...jobEnv({} as D1Database),MEDIA:r.bucket},'https://cdn.apimart.ai/video','bad','video')).rejects.toThrow(/large/);expect(r.stats().completed).toBe(0);expect(r.stats().aborted).toBe(1);}finally{fetcher.mockRestore();}});
 it('aborts multipart writes when R2 fails and allows a safe retry',async()=>{const bad=multipartBucket({failPart:true}),good=multipartBucket(),fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>videoResponse(6,true));try{await expect(storeProviderMedia({...jobEnv({} as D1Database),MEDIA:bad.bucket},'https://cdn.apimart.ai/video','key','video')).rejects.toThrow();expect(bad.stats().aborted).toBe(1);await storeProviderMedia({...jobEnv({} as D1Database),MEDIA:good.bucket},'https://cdn.apimart.ai/video','key','video');expect(good.stats().completed).toBe(1);}finally{fetcher.mockRestore();}});
 it('cannot overwrite failed and refunded status after a stale result upload',async()=>{const d=await readyJob();d.sqlite.exec("UPDATE generations SET stage='polling',provider_id='task_1'");const uploading=gate(),resume=gate(),r=multipartBucket({beforeComplete:async()=>{uploading.resolve();await resume.promise;}});let statusCalls=0;const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async(url)=>String(url).includes('/v1/tasks/')?Response.json({data:++statusCalls===1?{status:'completed',result:{videos:[{url:['https://cdn.apimart.ai/video']}]}}:{status:'failed'}}):videoResponse(1));try{const old=advanceJob({...jobEnv(d.db),MEDIA:r.bucket},d.id);await uploading.promise;d.sqlite.exec('UPDATE generations SET lease_until=0,next_poll=0');await advanceJob(jobEnv(d.db),d.id);resume.resolve();await old;expect(d.sqlite.prepare('SELECT status FROM generations').get()?.status).toBe('failed');expect(d.sqlite.prepare('SELECT credits FROM users').get()?.credits).toBe(100);}finally{resume.resolve();fetcher.mockRestore();}});
});
