// Videos generated by this site's Wan 3.0 Hotel Lobby template from original AI-generated
// character photos (2026-10-03). Replace the files in public/videos/lobbyduo and
// public/posters/lobbyduo when newer examples exist.
export type OwnExample = { id: string; src: string; poster: string; model: string; stage: string };

export const ownExamples: OwnExample[] = [
  { id: "wan-corgi-cat", src: "/videos/lobbyduo/wan-3-corgi-cat.mp4", poster: "/posters/lobbyduo/wan-3-corgi-cat.jpg", model: "Wan 3.0", stage: "Hotel Lobby" },
  { id: "wan-retriever-rabbit", src: "/videos/lobbyduo/wan-3-retriever-rabbit.mp4", poster: "/posters/lobbyduo/wan-3-retriever-rabbit.jpg", model: "Wan 3.0", stage: "Hotel Lobby" },
  { id: "wan-pug-raccoon", src: "/videos/lobbyduo/wan-3-pug-raccoon.mp4", poster: "/posters/lobbyduo/wan-3-pug-raccoon.jpg", model: "Wan 3.0", stage: "Hotel Lobby" },
];
