export type VideoExample = {
  id: string;
  title: string;
  src: string;
  poster: string;
  orientation: 'landscape' | 'portrait';
  sourceName: string;
  sourceUrl: string;
  homeFeatured: boolean;
};

export const videoExamples: VideoExample[] = [
  {
    id: "showcase",
    title: "Hotel Lobby template preview",
    src: "/videos/hotel-lobby-examples/showcase.mp4",
    poster: "/posters/hotel-lobby-examples/showcase.webp",
    orientation: "landscape",
    sourceName: "Media.io",
    sourceUrl: "https://www.media.io/ai/explore/zone/hotel-lobby-ai-video-trend",
    homeFeatured: false,
  },
  {
    id: "made-here-wan-1",
    title: "Hotel Lobby Video example 1",
    src: "/videos/hotel-lobby-examples/made-here-wan-1.mp4",
    poster: "/posters/hotel-lobby-examples/made-here-wan-1.webp",
    orientation: "landscape",
    sourceName: "Hotel Lobby Video",
    sourceUrl: "https://hotellobbyvideo.net/",
    homeFeatured: false,
  },
  {
    id: "made-here-wan-2",
    title: "Hotel Lobby Video example 2",
    src: "/videos/hotel-lobby-examples/made-here-wan-2.mp4",
    poster: "/posters/hotel-lobby-examples/made-here-wan-2.webp",
    orientation: "landscape",
    sourceName: "Hotel Lobby Video",
    sourceUrl: "https://hotellobbyvideo.net/",
    homeFeatured: false,
  },
  {
    id: "x-cats-ogfeitoza",
    title: "The cat version",
    src: "/videos/hotel-lobby-examples/x-cats-ogfeitoza.mp4",
    poster: "/posters/hotel-lobby-examples/x-cats-ogfeitoza.webp",
    orientation: "landscape",
    sourceName: "@ogfeitoza on X",
    sourceUrl: "https://x.com/ogfeitoza/status/2100991271695192335",
    homeFeatured: true,
  },
  {
    id: "x-chihuahuas",
    title: "Chewy and Rocky",
    src: "/videos/hotel-lobby-examples/x-chihuahuas.mp4",
    poster: "/posters/hotel-lobby-examples/x-chihuahuas.webp",
    orientation: "landscape",
    sourceName: "@chewychihuahua_ on X",
    sourceUrl: "https://x.com/chewychihuahua_/status/2101696601416704466",
    homeFeatured: true,
  },
  {
    id: "x-grandmas-aireel",
    title: "Grandma edition",
    src: "/videos/hotel-lobby-examples/x-grandmas-aireel.mp4",
    poster: "/posters/hotel-lobby-examples/x-grandmas-aireel.webp",
    orientation: "landscape",
    sourceName: "@AIReelofficial on X",
    sourceUrl: "https://x.com/AIReelofficial/status/2102844952132870445",
    homeFeatured: true,
  },
  {
    id: "noiz-anime-duo",
    title: "Anime duo",
    src: "/videos/hotel-lobby-examples/noiz-anime-duo.mp4",
    poster: "/posters/hotel-lobby-examples/noiz-anime-duo.webp",
    orientation: "landscape",
    sourceName: "Noiz",
    sourceUrl: "https://noiz.ai/lp/hotel-lobby",
    homeFeatured: true,
  },
  {
    id: "noiz-boxer-kangaroo",
    title: "Boxer and kangaroo",
    src: "/videos/hotel-lobby-examples/noiz-boxer-kangaroo.mp4",
    poster: "/posters/hotel-lobby-examples/noiz-boxer-kangaroo.webp",
    orientation: "landscape",
    sourceName: "Noiz",
    sourceUrl: "https://noiz.ai/lp/hotel-lobby",
    homeFeatured: true,
  },
  {
    id: "kling-guy-grim-reaper",
    title: "Guy and the grim reaper",
    src: "/videos/hotel-lobby-examples/kling-guy-grim-reaper.mp4",
    poster: "/posters/hotel-lobby-examples/kling-guy-grim-reaper.webp",
    orientation: "landscape",
    sourceName: "Kling Motion",
    sourceUrl: "https://klingmotion.ai/hotel-lobby-ai",
    homeFeatured: true,
  },
  {
    id: "lightx-dog-cat",
    title: "Animal buddies",
    src: "/videos/hotel-lobby-examples/lightx-dog-cat.mp4",
    poster: "/posters/hotel-lobby-examples/lightx-dog-cat.webp",
    orientation: "landscape",
    sourceName: "LightX",
    sourceUrl: "https://www.lightxeditor.com/blog/how-to-make-hotel-lobby-ai-video/",
    homeFeatured: true,
  },
  {
    id: "lightx-man-dog",
    title: "Man and his dog",
    src: "/videos/hotel-lobby-examples/lightx-man-dog.mp4",
    poster: "/posters/hotel-lobby-examples/lightx-man-dog.webp",
    orientation: "landscape",
    sourceName: "LightX",
    sourceUrl: "https://www.lightxeditor.com/blog/how-to-make-hotel-lobby-ai-video/",
    homeFeatured: true,
  },
  {
    id: "lightx-woman-cat",
    title: "Woman and her cat",
    src: "/videos/hotel-lobby-examples/lightx-woman-cat.mp4",
    poster: "/posters/hotel-lobby-examples/lightx-woman-cat.webp",
    orientation: "landscape",
    sourceName: "LightX",
    sourceUrl: "https://www.lightxeditor.com/blog/how-to-make-hotel-lobby-ai-video/",
    homeFeatured: true,
  },
  {
    id: "imageat-duo",
    title: "Streetwear duo",
    src: "/videos/hotel-lobby-examples/imageat-duo.mp4",
    poster: "/posters/hotel-lobby-examples/imageat-duo.webp",
    orientation: "portrait",
    sourceName: "imageat",
    sourceUrl: "https://imageat.com/trends/hotel-lobby-swap-ai-video",
    homeFeatured: false,
  },
  {
    id: "starrd-grandma",
    title: "Grandma and her grandson",
    src: "/videos/hotel-lobby-examples/starrd-grandma.mp4",
    poster: "/posters/hotel-lobby-examples/starrd-grandma.webp",
    orientation: "portrait",
    sourceName: "Starrd",
    sourceUrl: "https://www.getstarrd.app/template/hotel-lobby-extended-colors-show-ai-video",
    homeFeatured: false,
  },
  {
    id: "rapduo-friends",
    title: "Best friends at one mic",
    src: "/videos/hotel-lobby-examples/rapduo-friends.mp4",
    poster: "/posters/hotel-lobby-examples/rapduo-friends.webp",
    orientation: "portrait",
    sourceName: "Rap Duo",
    sourceUrl: "https://rapduo.ai/",
    homeFeatured: false,
  },
  {
    id: "fuzana-gym-buddies",
    title: "Gym buddies",
    src: "/videos/hotel-lobby-examples/fuzana-gym-buddies.mp4",
    poster: "/posters/hotel-lobby-examples/fuzana-gym-buddies.webp",
    orientation: "portrait",
    sourceName: "Fuzana",
    sourceUrl: "https://fuzana.com/en/free-tools/hotel-lobby-ai",
    homeFeatured: false,
  },
  {
    id: "fuzana-grandparents",
    title: "Grandparents take the booth",
    src: "/videos/hotel-lobby-examples/fuzana-grandparents.mp4",
    poster: "/posters/hotel-lobby-examples/fuzana-grandparents.webp",
    orientation: "portrait",
    sourceName: "Fuzana",
    sourceUrl: "https://fuzana.com/en/free-tools/hotel-lobby-ai",
    homeFeatured: false,
  },
  {
    id: "fuzana-newlyweds",
    title: "Just married",
    src: "/videos/hotel-lobby-examples/fuzana-newlyweds.mp4",
    poster: "/posters/hotel-lobby-examples/fuzana-newlyweds.webp",
    orientation: "portrait",
    sourceName: "Fuzana",
    sourceUrl: "https://fuzana.com/en/free-tools/hotel-lobby-ai",
    homeFeatured: false,
  },
  {
    id: "fuzana-grandma-and-granddaughter",
    title: "Grandma and granddaughter",
    src: "/videos/hotel-lobby-examples/fuzana-grandma-and-granddaughter.mp4",
    poster: "/posters/hotel-lobby-examples/fuzana-grandma-and-granddaughter.webp",
    orientation: "portrait",
    sourceName: "Fuzana",
    sourceUrl: "https://fuzana.com/en/free-tools/hotel-lobby-ai",
    homeFeatured: false,
  },
  {
    id: "fuzana-dad-and-son",
    title: "Dad and son",
    src: "/videos/hotel-lobby-examples/fuzana-dad-and-son.mp4",
    poster: "/posters/hotel-lobby-examples/fuzana-dad-and-son.webp",
    orientation: "portrait",
    sourceName: "Fuzana",
    sourceUrl: "https://fuzana.com/en/free-tools/hotel-lobby-ai",
    homeFeatured: false,
  },
  {
    id: "lightx-buddies",
    title: "Two friends",
    src: "/videos/hotel-lobby-examples/lightx-buddies.mp4",
    poster: "/posters/hotel-lobby-examples/lightx-buddies.webp",
    orientation: "landscape",
    sourceName: "LightX",
    sourceUrl: "https://www.lightxeditor.com/blog/how-to-make-hotel-lobby-ai-video/",
    homeFeatured: false,
  },
];

export const landscapeVideoExamples = videoExamples.filter(
  (example) => example.orientation === "landscape",
);

export const portraitVideoExamples = videoExamples.filter(
  (example) => example.orientation === "portrait",
);
