import type { Metadata } from "next";
import { LegalPage } from "@/components/sections/legal-page";

export const metadata: Metadata = { title: "Privacy Policy" };

const sections = [
  { id: "introduction", title: "Introduction", body: <p>Welcome to Migos AI, an online service for generating AI video and audio from your own creative inputs. This Privacy Policy describes the information collected when you use migosai.design, how it is used and shared, and the choices available to you. Use of the service is also subject to our <a href="/terms-of-service">Terms of Service</a>.</p> },
  { id: "information-collection-and-use", title: "Information Collection and Use", body: <><p>We collect information needed to operate, secure, and improve Migos AI:</p><h3>Account Information</h3><ul><li><b>What we collect:</b> Your name, email address, account identifier, and authentication details received from the sign-in provider.</li><li><b>Purpose:</b> To create and protect your account, recognize you when you return, and communicate about support or service issues.</li></ul><h3>AI Video and Audio Generation Data</h3><ul><li><b>What we collect:</b> Uploaded reference images, prompts, lyrics or style instructions, selected settings, generated media, task status, and related metadata.</li><li><b>Purpose:</b> To process your request, display or deliver results, troubleshoot errors, and manage your generation history.</li></ul><h3>Usage Details</h3><ul><li><b>What we collect:</b> Pages visited, features used, generation activity, credit transactions, and interaction data.</li><li><b>Purpose:</b> To operate the service, understand usage, prevent abuse, and improve reliability.</li></ul><h3>Device and Log Information</h3><ul><li><b>What we collect:</b> Device and browser type, IP address, referring URL, timestamps, and diagnostic logs.</li><li><b>Purpose:</b> To provide the service on different devices, maintain security, and investigate technical issues.</li></ul><h3>Cookies and Similar Technologies</h3><ul><li><b>What we collect:</b> Session cookies and other identifiers needed to remember account state and preferences.</li><li><b>Purpose:</b> To keep you signed in and support essential site functions. Optional analytics may be used if enabled and disclosed on the site.</li></ul><h3>Payment and Billing Information</h3><ul><li><b>What we collect:</b> Purchased pack, credits, order status, payment identifiers, and billing information supplied by our payment processor.</li><li><b>Purpose:</b> To process purchases, add credits, issue receipts, resolve payment questions, and prevent fraud. Migos AI does not store full card numbers.</li></ul></> },
  { id: "data-storage-and-security", title: "Data Storage and Security", body: <p>We apply technical and organizational measures intended to protect account details, uploaded images, and generated results. Access to stored content is restricted to the account owner and personnel or providers who need it to operate the service. No internet service can guarantee absolute security, so please use strong account protections and avoid uploading sensitive material you do not need to provide.</p> },
  { id: "information-sharing-and-disclosure", title: "Information Sharing and Disclosure", body: <><p>We do not sell your personal information. We may share limited information when needed to:</p><ul><li>Process payments through Creem and fulfill purchased credits.</li><li>Send generation inputs to the AI providers that create your video or audio.</li><li>Operate hosting, storage, authentication, security, and support functions through trusted service providers.</li><li>Comply with law, respond to valid requests, or protect the rights and safety of Migos AI and its users.</li><li>Complete a lawful business transfer, subject to appropriate safeguards.</li></ul></> },
  { id: "user-content", title: "User Content", body: <p>You are responsible for the images, text, audio instructions, and other content you upload. Please use material you own or have permission to use, and avoid including sensitive personal information unless it is necessary for your intended use. Generated output can depend on the input you provide and on the capabilities of the AI models used to provide the service.</p> },
  { id: "changes-to-this-policy", title: "Changes to This Policy", body: <p>We may revise this policy as Migos AI changes. The date above indicates the latest update. Material changes will be announced on this page or through another appropriate service notice. Continued use after the updated policy takes effect means the updated policy applies.</p> },
  { id: "contact-us", title: "Contact Us", body: <p>For privacy questions, access or deletion requests, or concerns about your data, use the support contact published on migosai.design. Please include enough information to identify your account without sending passwords or payment card numbers.</p> },
];

export default function PrivacyPolicyPage() { return <LegalPage title="Privacy Policy" subtitle="Privacy policy for Migos AI" sections={sections}/>; }
