import { SUPPORT_EMAIL, SUPPORT_MAILTO } from "@/content/support";
import Link from "@/components/i18n/localized-link";
import { getTranslations, localizeMetadata } from "@/lib/i18n/server";
import { localizePageContent } from "@/components/sections/localized-page-content";
import { LegalPage } from "@/components/sections/legal-page";

export async function generateMetadata() { return localizeMetadata({ title: "Terms of Service" }); }

const sections = [
  { id: "introduction-and-acceptance-of-terms", title: "Introduction and Acceptance of Terms", body: <p>Welcome to LobbyDuo, a service at migosai.design for creating AI-generated video and audio. These Terms of Service govern your access to and use of the website, generation tools, credits, and related features. By creating an account or using LobbyDuo, you agree to these Terms and our <Link href="/privacy-policy">Privacy Policy</Link>. If you do not agree, please do not use the service.</p> },
  { id: "use-of-the-service", title: "Use of the Service", body: <p>LobbyDuo provides tools for generating videos and songs from prompts, uploaded images, and selected settings. Use the service lawfully and follow any limits shown in the interface. The output of an AI system may vary from the prompt, and processing time and availability depend on demand, provider capacity, and technical conditions.</p> },
  { id: "user-accounts-and-registration", title: "User Accounts and Registration", body: <><p>Some features require an account. You agree to provide accurate account information and to keep access to your sign-in provider secure. You are responsible for activity under your account and for telling us promptly if you suspect unauthorized access.</p><p>We may suspend access where necessary to protect users, investigate abuse, respond to legal obligations, or enforce these Terms. You may stop using the service at any time.</p></> },
  { id: "eligibility-and-operator", title: "Eligibility and Operator", body: <><p>You must be at least 18 years old, or the age of majority where you live, to create an account or buy credits. If you upload content showing a minor, you must be that minor’s parent or legal guardian or have their permission.</p><p>LobbyDuo is operated independently at migosai.design. It is not affiliated with migosai.com or any similarly named service, and those services are not responsible for LobbyDuo accounts, orders or support.</p></> },
  { id: "ai-generation-inputs-and-outputs", title: "AI Generation Inputs and Outputs", body: <><p>You are responsible for the images, prompts, lyrics, and other inputs you submit. You must have the rights and permissions needed to upload and use them, including any consent required from people shown in photos. Do not submit content that infringes another person’s privacy, publicity, or intellectual property rights.</p><p>AI-generated outputs may be unexpected, inaccurate, or similar to outputs received by others. Review a result before publishing or relying on it. You are responsible for how you use and distribute the output.</p></> },
  { id: "content-and-intellectual-property-rights", title: "Content and Intellectual Property Rights", body: <><p>You retain any rights you have in your original inputs. You grant LobbyDuo and the providers involved in generation a limited permission to store, transmit, transform, and process your inputs and outputs to deliver the service, investigate errors or abuse, and meet legal requirements.</p><p>LobbyDuo’s name, interface, design, and software are owned by the service operator or its licensors. These Terms do not transfer those rights to you. Generated media may be subject to restrictions under applicable law or third-party rights. You are responsible for checking that any intended commercial or public use is permitted.</p><ul><li>Do not upload images of another person without appropriate consent.</li><li>Do not use copyrighted music, characters, or other materials without permission.</li><li>Do not present a generated performance as a real statement or endorsement by a depicted person.</li></ul></> },
  { id: "prohibited-activities", title: "Prohibited Activities", body: <><p>You agree not to use LobbyDuo to:</p><ul><li>Upload or generate illegal, abusive, exploitative, or non-consensual intimate content.</li><li>Violate another person’s privacy, publicity, copyright, trademark, or other rights.</li><li>Impersonate someone in a way likely to deceive, defraud, or harm others.</li><li>Distribute malware, spam, or content intended to compromise the service or other users.</li><li>Attempt to bypass account limits, credit charges, security measures, or access controls.</li><li>Reverse engineer, scrape, overload, or disrupt the service except as permitted by applicable law.</li><li>Resell access or use generated content in a way that violates these Terms or applicable law.</li></ul><p>We may reject requests, restrict delivery, remove content, or suspend accounts to address violations. Our Acceptable Use Policy forms part of these Terms.</p></> },
  { id: "privacy-and-data-collection", title: "Privacy and Data Collection", body: <><p>Our <Link href="/privacy-policy">Privacy Policy</Link> describes how information is collected, used, and shared. By using the service, you acknowledge that generation inputs and outputs may be processed by providers needed to deliver the requested video or audio.</p><ul><li>Account information is used to authenticate and support your access.</li><li>Uploaded media and prompts are processed to create the requested output.</li><li>Stripe processes new payments; we receive the transaction details needed to manage orders and credits. We do not store full payment card numbers.</li><li>Usage and diagnostic data help us keep the service reliable and secure.</li></ul></> },
  { id: "pricing-credits-and-payments", title: "Pricing, Credits, and Payments", body: <><p>LobbyDuo offers one-time credit packs at the prices displayed on the Pricing page. Credits are deducted according to the amount displayed before a generation request is submitted. Prices and credit costs may change for future purchases or requests; already purchased credits remain recorded in your account.</p><ul><li>New credit-pack purchases use Stripe Checkout. These are one-time payments, with no subscription or automatic renewal. Credits are added after payment is verified.</li><li>Credits are used for eligible generation requests and are not cash or transferable property.</li><li>Where a request fails without a completed output, we will restore credits according to the service’s failure handling rules.</li><li>Completely unused credit packs may qualify for a refund when requested within 14 days of purchase. See our Refund Policy for eligibility, failed generations, and payment issues.</li></ul></> },
  { id: "models-and-ai-disclosure", title: "AI Models and Disclosure", body: <><p>New videos use Wan 3.0, Seedance 2.0, or Seedance 2.0 Fast through Kie. APIMart provides music generation and processes historical video jobs. Available models and features may change.</p><p>Outputs are AI-generated performances, not recordings of real events or endorsements. Follow the AI-labeling rules of the platforms where you share them. LobbyDuo is independent and has no affiliation, sponsorship, or endorsement from Migos, Quavo, Takeoff, Quality Control Music, Motown, or COLORS.</p><p><Link href="/acceptable-use-policy">Acceptable Use Policy</Link> · <Link href="/refund-policy">Refund Policy</Link></p></> },
  { id: "service-availability", title: "Service Availability", body: <p>We aim to keep LobbyDuo available, but generation depends on external systems, network conditions, and maintenance. We may change, pause, or discontinue a feature where needed for security, performance, legal compliance, or product improvement. We do not guarantee that every request will produce a usable result.</p> },
  { id: "termination", title: "Termination", body: <p>You may stop using the service at any time. We may restrict or end access if you materially violate these Terms, create risk for others, or if required by law. Where practical, we will provide notice and a way to raise questions about the decision.</p> },
  { id: "disclaimer-of-warranties", title: "Disclaimer of Warranties", body: <p>To the extent permitted by law, LobbyDuo is provided on an “as available” basis. We do not promise uninterrupted operation, error-free generation, or that output will meet every creative or commercial purpose. Nothing in these Terms excludes rights or warranties that cannot legally be excluded.</p> },
  { id: "limitation-of-liability", title: "Limitation of Liability", body: <p>To the extent permitted by applicable law, LobbyDuo and its providers are not liable for indirect or consequential losses arising from use of the service. Any limits on liability apply only where allowed by law and do not affect rights that cannot be waived.</p> },
  { id: "indemnification", title: "Indemnification", body: <p>Where permitted by law, you agree to address claims arising from content you submit or your unlawful use of the service, including claims that your inputs or publication of outputs violated another person’s rights. This provision does not apply to losses caused by our own unlawful conduct.</p> },
  { id: "governing-law-and-dispute-resolution", title: "Governing Law and Dispute Resolution", body: <p>Please contact our support team to discuss a dispute. Applicable mandatory consumer protections remain in force; nothing in these Terms removes rights that cannot be waived under your local law.</p> },
  { id: "changes-to-these-terms", title: "Changes to These Terms", body: <p>We may update these Terms as the service evolves. The date above shows the latest revision. Material changes will be announced on this page or by another appropriate notice, and the updated Terms apply from the stated effective date.</p> },
  { id: "contact-information", title: "Contact Information", body: <><p>For support, policy questions, refunds, or content reports, email the address below. Include your account email and any relevant order or generation ID. Never send passwords or full payment card details.</p><p><a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a></p></> },
];

export default async function TermsOfServicePage() {
  const t = await getTranslations(); return localizePageContent(<LegalPage title="Terms of Service" subtitle="Terms of service for LobbyDuo" sections={sections}/>, t); }
